server:
  port: 9000

logging:
  level:
    org.springframework.security: info

spring:
  config:
    import:
      - application_db.yml
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000


